### ISSUE TITLE
Support for Occlusion Portals

### ISSUE THREAD

**Issue by squiddingme** [MMMaellon/real-fake-doors#1]
It would be a nice feature for doors to support [Occlusion Portals](https://docs.unity3d.com/2019.4/Documentation/Manual/class-OcclusionPortal.html). When a door is fully closed, toggle the occlusion portal on to occlude anything behind the door. This can be implemented as a custom DoorListener, but built-in support might be something to consider.

**Comment by MMMaellon** [comment]
Great idea. Adding support for it in version 1.4.0
